### ISSUE TITLE
Tracks broken in production RnP

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#100]
tracks for "Elk City" by All the Real Girls do not play in RnP, nor does the "update duration" button work. the tracks **do** play in Complete Submission, and appear to be normal 'ol wav files. 

tested in Kreg's account in Chrome (by Kreg) and in Valerie's account in Firefox (by me)

https://playback.spl.org/admin/review-and-publish/submissions/albums/all-the-real-girls-elk-city

**Comment by kellyhiser** [comment]
@prestonaustin please reassign to Bill if needed.

**Comment by kellyhiser** [comment]
I originally reported this bug as being for a specific album, but ALL tracks in RnP do NOT playback. The "update duration" button does not work.

**Comment by whblondeau** [comment]
Report on possible javascript console log reveal of the issue was emailed.

**Comment by kellyhiser** [comment]
@prestonaustin and @whblondeau NB: it's the night of August 1, I've been clicking around in RnP for a few minutes, and I've yet to encounter a track that will not play. Everything seems to be working just fine, including tracks that have a zero duration (their progress bar fills immediately, but they play normally).
