### ISSUE TITLE
tracks in Jason Parker Quartet are weird

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#116]
https://playback.spl.org/albums/jason-parker-quartet-homegrown

all tracks are glitchy: they have random pauses and periods of static - I'm guessing this is a file problem, not a MUSICat problem (and not a super-avant-guard thing). Should I reach out to artists and get new files?

**Comment by prestonaustin** [comment]
I missed this this afternoon, sorry. Yes we should try to get new source
files, ideally WAV or something from a clean CD rip, and replace the tracks
and republish.

**Comment by kellyhiser** [comment]
K, I'm on it. Thanks!

**Comment by kellyhiser** [comment]
done.
