### ISSUE TITLE
Links or screenshots of CCR submission and jury interfaces for SPL?

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#16]
@mbrakken Can I get shareable links or screenshots of the submission and jury interfaces that CCR uses for SPL? They want to get a sense of what the process looks like.

/cc @prestonaustin

**Comment by mbrakken** [comment]
@lahollen Current URL is https://capitalcityrecords.ca/submit. EPL has asked for a screen before this which lays out general information that an artist opts in to. I may just add that info to the top of the current interface.

Screenshots:

![submit_an_album_to_capital_city_records_-_2015-10-26_10 32 26](https://cloud.githubusercontent.com/assets/1530955/10733467/fc0b9196-7bcc-11e5-817e-cc3bcd1c7d4c.png)
![submit_an_album_to_capital_city_records_-_2015-10-26_10 33 16](https://cloud.githubusercontent.com/assets/1530955/10733472/fee5e146-7bcc-11e5-8c9e-91295b0d51ce.png)

Last version of the jury interface looked more or less like this:

![capital_city_records_-_music_submissions_-_2015-02-12_16 48 18](https://cloud.githubusercontent.com/assets/1530955/10733586/7ff59326-7bcd-11e5-8cb7-c5ed1cccc426.png)

I have a reworked concept I'm trying to get out for this round, which will roughly look like this:

![20151019_141420](https://cloud.githubusercontent.com/assets/1530955/10733630/96244e8a-7bcd-11e5-9e8b-e94c6afe3511.jpg)

**Comment by lahollen** [comment]
Thanks! @andrewharbison this is for your reference. I also created a Google Doc with links to these references that you can share with others. 

https://docs.google.com/document/d/1TPKgcg9xrMLLQ5BWBU71yvqwsI1oxqRG-2NlzOacDN0/edit?usp=sharing

**Comment by lahollen** [comment]
Closing this issue but materials still available to view.
