### ISSUE TITLE
Get SPL contacts

### ISSUE THREAD

**Issue by mbrakken** [therabble/seattle-public-library-client#2]
- [x] Acting project manager - Andrew Harbison; andrew.harbison@spl.org
- [x] DNS contact - Lisa Zicherman; lisa.zicherman@spl.org
- [x] Designer - Annie Vazquez; annie.vasquez@spl.org
- [x] Contact for authentication for library card holders (2) - 
1. Kirk Blankenship, Electronic Resources Librarian; kirk.blankenship@spl.org
2. Lare Mischo, Systems Librarian; lare.mischo@spl.org

**Comment by lahollen** [comment]
@andrewharbison these are some of the folks we'd like to know at Seattle. We can bring all or some into this repository if/when you know them. (I know the project lead is still TBD)
