### ISSUE TITLE
Add capability for artists to choose between 2 licenses

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#20]
Artists will have choice to sign either 5-year or perpetual license in submit-the-things interface. Need new capability in interface for artist to choose an option and then have the correct license populate with data.

**Comment by lahollen** [comment]
May also have creative commons option a la CCR - see #9

**Comment by lahollen** [comment]
5-year term license: https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit

Perpetual term license: https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit#

Licenses are formatted the same and mostly identical, except for language involving term limits.

YES to Creative Commons option.

**Comment by prestonaustin** [comment]
Blocked by issue 70.

**Comment by prestonaustin** [comment]
No longer blocked. Bill is working on radio selector today.

**Comment by prestonaustin** [comment]
MOVED HERE FROM ISSUE 70 TO SEPARATE FUNCTIONAL CONCERN

- [ ] **ADD NEW SUB-SECTION** WITH CAPABILITY FOR ARTISTS TO CHOOSE BETWEEN THE 2 LICENSES. **SUGGESTED COPY AND FORMATTING:**

#### Select Your License
Choose one of the following licensing agreements, and review closely the license that is created for you.

- [ ] [Five-year term license] (https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit?usp=sharing) 
- [ ] [Perpetual term license] (https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit?usp=sharing)

Optional [Creative Commons Attribution 4.0 International Public License] (https://creativecommons.org/licenses/by/4.0/)
- [ ] Include Creative Commons Attribution 4.0 International Public License

[SELECTED AND COMPLETED LICENSE]

**Comment by whblondeau** [comment]
Able to display alternative template content, but without the "article" tags. Trying to find out why.

**Comment by whblondeau** [comment]
Halting for now - mental tiredness is making it too likely I will break something.

WHAT WORKS:
  - [x] Initial presentation of page when there's no previously chosen license (default 5 yr license)
  - [x] Correct license template displayed in form, depending on radio button selected
  - [x] Saved license stashes datestring for chosen license

WHAT DOESN'T WORK:
  - [ ] Initial presentation of page when a license HAS been previously saved:
    - [ ] Radio buttons should not be shown (can't go back on your choice) for 
      - a previously SIGNED license (even if you unsign it)
      - that is PERPETUAL
    - [ ] Template should show the form of the license that was chosen at last save.
  - [ ] Confirmation email template does not state which license was actually chosen.

Probably more, but the hardest part is over, I think. I now understand the basic arrangement of data and forms.

**Comment by whblondeau** [comment]
All reported issues are copy & presentation, not logic of selecting a license and having the license correctly represented onscreen. Done.
