### ISSUE TITLE
Reporting requirements - logging inbound links

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#22]
Log HTTP referer to main site.

**Comment by lahollen** [comment]
SPL will use Google Analytics to track this.

**Comment by kellyhiser** [comment]
we'll need to link setting up GA for SPB to the reporting milestone.

**Comment by lahollen** [comment]
there is no reporting milestone in GH unless we want to create one, but i'll add it to the reporting issue i created

**Comment by kellyhiser** [comment]
no, let's not and just tie to public launch as you're already doing. thanks!
