### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by mbrakken** [therabble/seattle-public-library-client#3]
What is the app called?

**Comment by lahollen** [comment]
Update: team is working to finalize crowdsourced name from shortlist. Assigning to @andrewharbison to update here on decision and/or delays.

**Comment by andrewharbison** [comment]
Name is Sound Waves.

**Comment by lahollen** [comment]
Sweet! I like it. Rabble team will regroup tomorrow to talk setup.

**Comment by andrewharbison** [comment]
Great. We live in the Puget Sound (to explain it)...

**Comment by prestonaustin** [comment]
Excellent! Should the project initials be PSW then?

(Only the cool people will know what the P is about :)
