### ISSUE TITLE
Add SPL Foundation logo to site footers

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#30]
SPL requests that we add the Foundation logo to their site. Located in shared drive here: https://drive.google.com/open?id=0B2JtTtreF1SzcXkwcmFZWEJyTVdsa3FtNldOOWdKZUFMRGx3

**Comment by kellyhiser** [comment]
@prestonaustin just a reminder of this as you work on skinning the site today.

**Comment by prestonaustin** [comment]
Already done on a branch. Will deploy sometime today.
