### ISSUE TITLE
playback not working in Invite interface

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#40]
for MAPLE LEAF PUTIN track on the Hee Haw album. Playback works in the Jury panel. duration for the track is 0

Chrome, 4/27, 8:30 PM ET

JavaScript console reads:

Failed to load resource: the server responded with a status of 404 (Not Found) https://playback-api.spl.org/public/albums/

**Comment by kellyhiser** [comment]
April 28 10:15 AM, now this album doesn't appear anywhere in the admin interfaces.

**Comment by prestonaustin** [comment]
Can this be closed?

**Comment by kellyhiser** [comment]
No, playback still isn't working in the invite interface - I just tried a
different record, Testing Testing by Kelly. Not critical that we fix now.

On Thu, Apr 28, 2016 at 11:08 AM, Preston Austin <notifications@github.com>
wrote:

> Can this be closed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/therabble/seattle-public-library-client/issues/40#issuecomment-215456656>
>



-- 
Kelly Hiser

CEO, Rabble
MUSICat.co

Ph.D. Historical Musicology
University of Wisconsin-Madison

**Comment by lahollen** [comment]
@prestonaustin Can this be closed?

**Comment by prestonaustin** [comment]
It's not a specified feature of this stage, more just a side effect of
track UI component reuse, so I don't think it blocks and we might take it
off the invite milestone.

That said, I would like to address it soon, simply to make the UX nicer and
allow inviter to quick check tracks without leaving the invite interface if
they wish to, so let's not close it.
