### ISSUE TITLE
Users unable to access playback-wax

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#47]
@ksellers was not able to access https://playback-wax.spl.org/submit.

Kate is on on Windows 7, tested using Chrome (Version 50.0.2661.94 m) and IE 11. Fri 5/6, around 1:10pm CT. Screenshots of error reports attached.

![image002](https://cloud.githubusercontent.com/assets/13225403/15082380/002dd79a-138d-11e6-957c-6b9e0980a261.png)
![image001](https://cloud.githubusercontent.com/assets/13225403/15082381/002f936e-138d-11e6-9c1f-4795c41220e3.jpg)

**Comment by mbrakken** [comment]
FWIW, I just successfully hit https://playback-wax.spl.org to test. Maybe
local connectivity issues?

**Comment by ksellers** [comment]
I'm getting to other sites just fine, but will log off/back on to see if that resets things. Other staff here in the same building haven't been able to reach - any chance there might be something in our firewall or other security that is blocking us? I can report to our IT if needed.

**Comment by mbrakken** [comment]
*Could* be something firewall-related, but I don't know much about those
sorts of things. Maybe an issue at the ISP? I know there was one afternoon
where no one in my office could access github, but people elsewhere had no
problems. All that stuff is definitely not my domain of expertise.

**Comment by kellyhiser** [comment]
Just tried to access via my hub's PC and got the same message Kate did. more info in a sec...

**Comment by ksellers** [comment]
I just tested on my phone, and I could get to it just fine, so it's definitely an issue on our end or with PCs.

**Comment by kellyhiser** [comment]
Windows 10, Chrome

console sez: 

http://playback.wax.spl.org/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://playback.wax.spl.org/:1 GET http://playback.wax.spl.org/ net::ERR_NAME_NOT_RESOLVED

**Comment by prestonaustin** [comment]
This looks like a DNS lookup issue, which suggests whatever DNS servers the
clients in the building point at don't like how we set it up. (Which I
dimly recall maybe Andrew had an issue with like 18 months ago)

I checked and DNS is up and configure the way we think it should be, so
asking someone in IT to track down what the local DNS service doesn't like
would be helpful.

So you understand what is set up now:

playback-wax.spl.org is a CNAME to playback-wax.spl.org.musicat.co

playback-wax.spl.org.musicat.co is a CNAME to lb.murfie.com

lb.murfie.com is a load balancer and SSL proxy that has the SSL certificate
registered on it, the other names resolve to this server. It actually
accepts the connection from the web browser, handles SSL decryption, and
directs queries to the application server and responses back to the
client/web browser.

So, a properly resolving DNS request for an IP address for playback or
playback-wax.spl.org should yield the same IP address as a lookup of
lb.murfie.com at all times from all clients. playback-wax.spl.org.musicat.co
lookups should also yield that IP address.

What you are seeing suggests to me that your clients' DNS nameservice name
server is refusing to follow one of the CNAMES. If it's locally hosted DNS
nameservice, that maybe because it won't go to external DNS nameservice
hosts to resolve something it expects to be able to resolve within its own
spl.org domain. This can be a result of a security policy designed to
prevent sorts of DNS based hijacking of client connections.

Question: Do you have the same error message if you go to each of

1. playback.spl.org (should get the playback website)

2. playback-wax.spl.org.musicat.co (should get a different error)

3. lb.murfie.com (should get a different error)

Thanks,
Preston

**Comment by prestonaustin** [comment]
Kelly: are you entering playback-wax or playback.wax? The latter should
fail, doesn't exist. All the names have to be <name>.spl.org or SPL would
need to buy a new wildcard certificate for a custom app domain.

**Comment by ksellers** [comment]
1 - testing playback.spl.org gets me the same error as the wax site.

2 - I get this error message: 
![playbackerror1](https://cloud.githubusercontent.com/assets/19212503/15083159/8c377550-1380-11e6-87aa-e39c3a6b9066.PNG)

3 - I get this error message:
![playbackerror2](https://cloud.githubusercontent.com/assets/19212503/15083176/ac6178f8-1380-11e6-93ee-f8098eca2bb4.PNG)

**Comment by kellyhiser** [comment]
@prestonaustin you're right, I was entering the latter. the former works for me in Chrome, on Windows 10. *smacks forehead*

**Comment by ksellers** [comment]
okay, so it's definitely an issue with our setup somehow. is there language I can use to set up a ticket with our IT that will explain this and how they can fix it?

**Comment by prestonaustin** [comment]
@kellyhiser - good, your result preserves my sense that there is logic and reason in the universe :)

@ksellers - those barracuda DNS cache responses definitely seem implicated here. Do you have an admin who can look into it? That said, I'm actually quite surprised by the error on lb.murfie.com. Can you connect to just murfie.com?

**Comment by lisazicherman** [comment]
Hi Preston
We set up the DNS as follows:
List of CNAME records to set up:
The API
playback-api.spl.org<http://soundwaves-api.spl.org> --> playback-api.spl.org.musicat.co<http://soundwaves-api.spl.org.musicat.co>
File storage
playback-jsfs.spl.org<http://soundwaves-jsfs.spl.org> --> playback-jsfs.spl.org.musicat.co<http://soundwaves-jsfs.spl.org.musicat.co>
Logging server
playback-log.spl.org<http://soundwaves-log.spl.org> --> playback-log.spl.org.musicat.co<http://soundwaves-log.spl.org.musicat.co>
File transcoder
playback-mms.spl.org<http://soundwaves-mms.spl.org> --> playback-mms.spl.org.musicat.co<http://soundwaves-mms.spl.org.musicat.co>
Transcoded file cache
playback-mmscache.spl.org<http://soundwaves-mmscache.spl.org> --> playback-mmscache.spl.org.musicat.co<http://soundwaves-mmscache.spl.org.musicat.co>
Temporary submissions app
playback-submissions.spl.org<http://soundwaves-submissions.spl.org> --> playback-submissions.spl.org.musicat.co<http://soundwaves-submissions.spl.org.musicat.co>
Test app
playback-wax.spl.org<http://soundwaves-wax.spl.org> --> playback-wax.spl.org.musicat.co<http://soundwaves-wax.spl.org.musicat.co>
Production app
playback.spl.org<http://soundwaves.spl.org> --> playback.spl.org.musicat.co<http://soundwaves.spl.org.musicat.co>
This is the info I got back from the Network Admin as confirmation:

Fyi: the entries I used for external dns (bind nameserver database file entries) are:

; external audio services for Lisa (MOS)
playback-api            IN      CNAME playback-api.spl.org.musicat.co.
playback-jsfs           IN      CNAME playback-jsfs.spl.org.musicat.co.
playback-log            IN      CNAME playback-log.spl.org.musicat.co.
playback-mms            IN      CNAME playback-mms.spl.org.musicat.co.
playback-mmscache       IN      CNAME playback-mmscache.spl.org.musicat.co.
playback-submissions    IN      CNAME playback-submissions.spl.org.musicat.co.
playback-wax            IN      CNAME playback-wax.spl.org.musicat.co.
playback                IN      CNAME playback.spl.org.musicat.co.

I will check in with him and see if he sees anything going wrong… Stay tuned.
Lisa Z

**Comment by ksellers** [comment]
@prestonaustin I couldn't connect to just murfie.com either

@lisazicherman Thanks, Lisa! Let me know if I can help at all on our end.

**Comment by prestonaustin** [comment]
@ksellers Proposed language: "Our barracuda caching firewall doesn't seem to like how DNS is setup for playback-wax.spl.org. Can you look at its logs and config, and let Preston at the Rabble know what you find?"

Can't be real specific yet I'm afraid, I'm a bit in the dark on what's blocking there.

**Comment by ksellers** [comment]
@prestonaustin thanks! Lisa Z. is going to check with our folks and see what we can do.

**Comment by ksellers** [comment]
@prestonaustin just had a thought - we didn't have trouble accessing the site previous to the latest update - did anything change that may have affected this?

**Comment by prestonaustin** [comment]
@ksellers I didn't change anything in DNS or load balancer configuration today, or recently. I could check when we did reconfigure it but I believe it was two weeks ago. I did update site content today, but that shouldn't change the access path.

To confirm: you can't see playback.spl.org either right now, correct?

@mbrakken - have you updated the Murfie load balancer recently?

**Comment by mbrakken** [comment]
@ksellers, do you roughly know when you / others last accessed playback.spl.org from inside the library? Nothing in today's update should have affected anything at the network / DNS layer, but if we know a general window of time I can see if there have been changes within that time that may affect things.

The fact that you also cannot access murfie.com seems quite strange. I assume you are able to access other sites / web servers from inside the library?

**Comment by ksellers** [comment]
@prestonaustin Hmmm. No, I can't access playback.spl.org either - same error message as the wax site.

@mbrakken Yes, we accessed it yesterday via a library computer without any issues, around 11 am our time.

**Comment by mbrakken** [comment]
@prestonaustin Last update to the LB (haproxy) in question was 10 days ago. That was to point capitalcityrecords.ca to the new server.

**Comment by mbrakken** [comment]
Thanks, @ksellers, definitely nothing went out since yesterday on our / Murfie's end that should be causing this.

**Comment by ksellers** [comment]
Okay, I'll report to our IT, we'll see what we can do.

**Comment by prestonaustin** [comment]
If Rabble needs to change the .spl.org.musicat.co namespace to something else to deconfuse barracuda, that's an option, so long as your .spl.org records can be updated today. This may offer your IT some latitude, but we shouldn't do it if they don't need it done.

**Comment by ksellers** [comment]
This appears to be fixed! From our IT: "I had been able to find the CNAMES (aliases) but not the Host record with the IP addresses. What appears to have fixed this internally was clearing musicat.co from the Cached Lookups on our internal DNS servers. Apparently the servers/IPaddresses had changed on Rabble’s end recently from what I understand. Therefore our DNS seems to have been caching the old server IP’s. It is now resolving to lb.murfie.com [130.211.123.35]. Clearing the cached lookups forces the DNS to go out and find the actual host name."

**Comment by prestonaustin** [comment]
Yay! Once you see it with your own eyes please close this ticket, but
re-open it if problems re-surface. There is another way we can do this if
it seems like the .spl.org.musicat.co names are causing a problem on the
library's nameserver cache. And, please convey my thanks to your IT! If
they need any info from us, I'm happy to provide it.

**Comment by ksellers** [comment]
Will do, on all counts :)
