### ISSUE TITLE
Edits to copy and links in submissions interface

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#49]
This is a list of copy edits and link fixes for the submissions pages. Apologies for errors that are due to my delivery of content.

Edits to Submission landing page at https://playback-wax.spl.org/submit:
- [x] Change dates of submission period to May 9 to May 23, 2016.
- [x] Link to FAQ currently goes to "About." Change link to FAQ: https://playback-wax.spl.org/faq
- [x] Links to five-year and perpetual license and plain-language license currently go to "About" page, which does not contain any licensing information. This is due to an error I made in collecting license information separately and not adding to "About" page copy a la CCR. The edits below to "About" page should correct this.
- [x] All instances of "Seattle Public Library" should read "The Seattle Public Library" or "Library" in second mention. This page requires the following edits: "Submit to The Seattle Public Library's PlayBack"; "All information you provide on this form is covered by The Seattle Public Library's Confidentiality of Patron Information"; "Both will allow Library cardholders to stream music and download"

Edits to "About" page https://playback-wax.spl.org/about:
- [x] Edit formatting of collection name in title and other copy: “About PlayBack"; "Through PlayBack, you can"
- [x] In second paragraph add "The" to "Seattle Public Library cardholders"
- [x] Add period after hyperlinked "here" in 3rd paragraph.
- [x] Add Licensing Information section. Copy located here w/ plain language and links to licenses: https://docs.google.com/document/d/160Z-QptBN0dHYC3i7qHVf_AeznH2-uX6DLuMbRAzBo8/edit?usp=sharing

Edits to "FAQ" page https://playback-wax.spl.org/faq:
- [x] "What is the submissions process..." question: Add hyperlinks to Twitter https://twitter.com/SPLBuzz and Facebook https://www.facebook.com/SeattlePublicLibrary/
- [x] "What is the submissions process..." question: Format of collection name in final sentence from Playback to PlayBack.
- [x] "What formats will Playback collection" question: Format collection name in question to PlayBack
- [x] "What if my music is represented..." question: Format collection name in answer to PlayBack
- [x] "I'm from out of town..." question: Delete this second sentence in answer with EPL text: "You are welcome to adapt our license agreement to your own context and feel free to contact EPL with any questions you have."

Edits to submissions form https://playback-wax.spl.org/submit/album-data:
- [x] Where files can be uploaded, there is a word missing at the start of the sentence: "will collect full albums" should be "We will collect full albums"

Edits to thank you message after submission https://playback-wax.spl.org/submit/thankyou:
- [x] Format collection name to PlayBack: "Your submissions has been uploaded to PlayBack"
- [x] Change link for "license agreement" to https://playback-wax.spl.org/about?anchor=license-summary. (Edits to "About" page above affect this.)
- [x] Change email contact to playback@spl.org

**Comment by ksellers** [comment]
On the /submit/thankyou page after someone submits tracks, we need to update the email address listed to "playback@spl.org" instead of "localmusic@spl.org"

The link from there to the license agreement info goes to blank page currently.

**Comment by ksellers** [comment]
Not sure if this should be a separate issues, but all instances of "Seattle Public Library" need to be "The Seattle Public Library".

**Comment by lahollen** [comment]
Thanks @ksellers. @prestonaustin I will edit the list above to reflect these additional copy changes.

**Comment by ksellers** [comment]
On playback-wax.spl.org/submit/album-data, where files can be uploaded, there is a word missing at the start of the sentence:

"will collect full albums" should be "We will collect full albums"

**Comment by prestonaustin** [comment]
@lahollen @ksellers 

On this request above:
Where files can be uploaded, there is a word missing at the start of the sentence: "will collect full albums" should be "We will collect full albums"

This was actually an error in my code, the original copy was supposed to read "PlayBack will..." so I made it that rather than "We" as requested here. I can still later change that to "We will..." if you prefer that to original copy. I've marked it done, just add the change again in a new comment if I should go with "We"

**Comment by prestonaustin** [comment]
OK, I'm deploying the items checked off above now, the others I will do as early as possible on Saturday and update here when I'm done. I'll also be checking things for consistency on Saturday.

If you find new issues, the easiest way to report them is just give me this format, without even telling me what page it is on:

Change: "a whole chuck of text I can find verbatim" to "a whole new chunck of text"
Add "formatted text to add" before/after/above/below "other text that helps me find it"
Link "existing words" near "words I can search for" to "http://some.url"

It's fine to tell me to add text, then tell me to link it, in two separate instructions and actually makes it faster :)

Thanks everyone for the super fast and organized turn around on review and the fix to DNS scare this afternoon, I know this is a delayed delivery on my part and I really appreciate the help getting everything proper for a nice orderly opening of submissions on Monday :)

**Comment by lahollen** [comment]
@prestonaustin Deployed changes look great! 

The submissions form still appears to have the code error you identified -- it only reads "will collect full albums, but right now..." It's fine for it to read as you intended ("PlayBack will...") but I'm unchecking it in the task list since code is maybe still an issue. Let me know if you'd like me to create a new issue for that one.

**Comment by prestonaustin** [comment]
Update: This is basically done. Won't deploy for a while because of some other breaking changes that I can't deploy yet today. We should consider pulling the licenses into source control from google, linking there feels wrong for the long haul (but not a submissions ready concern imo). I'll be making some little improvements to links and anchors.

If you notice anything that should be linked and isn't, or is linked some places and not others, I think we need to smooth that out here. I'll just fix what I find as I find it. Otherwise, open new issues for new edits. Thanks!
