### ISSUE TITLE
Additional tidying up for submissions 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#52]
- [x] remove "login" link until it works and makes sense to do so
- [x] link the home page to submit
- [x] remove artist and album pages until collection launch
- [x] consider moving About and FAQ to main nav section until collection launch

**Comment by prestonaustin** [comment]
- [ ] also fix ugly mobile footer format side-effect of nav updates

**Comment by prestonaustin** [comment]
- [ ] give better "no collection yet" feedback on search

**Comment by prestonaustin** [comment]
Probably I should outright redirect the homepage. I'm going to deploy and ensure other things are in great shape, and revisit that later.
