### ISSUE TITLE
Change licensing links

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#55]
Change links to 5-year and perpetual licenses on submissions landing page.

Link "five year" near "There are two licensing term options to choose from: five year and perpetual" to https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit?usp=sharing

Link "perpetual" near same as above to https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit?usp=sharing

**Comment by prestonaustin** [comment]
Closed, will go out in next deploy.
