### ISSUE TITLE
Consider adding graphic to homepage

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#58]
If we'd like to add a visual to liven up playback.spl.org, SPL suggests this image currently being used for social media promotion. Also located in the shared drive.
![facebook playback 750x246](https://cloud.githubusercontent.com/assets/13225403/15123772/cbb41988-15ea-11e6-9ded-d9d4bdeba524.jpg)

**Comment by prestonaustin** [comment]
Closed by https://github.com/therabble/seattle-public-library-client/pull/62
