### ISSUE TITLE
Restrict submissions form to allow only one track upload

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#59]
Change submissions form to request and allow only 1 representative track from each artist, instead of 1-3. 

This will also impact the text in the upload area from "PlayBack will collect full albums, but right now we only ask for a few sample tracks.Tracks submitted now will be shared with the jury, but will not be publicly released. Preferred file types: FLAC, WAV, ALAC, mp3, aac, ogg, oga, or aiff. Play each of your tracks to make sure they uploaded successfully." --> to --> "PlayBack will collect full albums, but right now we only ask for one representative track. Tracks submitted now will be shared with the jury, but will not be publicly released. Preferred file types: FLAC, WAV, ALAC, mp3, aac, ogg, oga, or aiff. Play your track to make sure it uploaded successfully."

**Comment by lahollen** [comment]
From @andrewharbison: "Is it possible to at least state in the submission form that we'll accept the best single/one representative track from the album?"

@prestonaustin I'm assuming the form will be restricted to one track today. However, if there's any difficulties doing so, change the text in the upload box anyway as described above to ask for only one track even if system is still allowing 3.

**Comment by lahollen** [comment]
Additional copy to change in either scenario: FROM "Please enter album info above before uploading tracks." --> to "Please enter album info above before uploading a representative track."

**Comment by prestonaustin** [comment]
https://github.com/therabble/seattle-public-library-client/pull/62
