### ISSUE TITLE
Design standards guide

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#6]
Do you have a shareable design standards guide?

**Comment by lahollen** [comment]
@mbrakken - SPL may not have a project logo ready in time for the submissions interface, but are willing to go ahead without it in the first round. Is this workable? What other design elements do you need? List here and I'll follow up.

**Comment by prestonaustin** [comment]
Let's use MUSICat defaults in all places where we have not yet applied
localized identity assets, to keep the look and feel solid and be testing
"real" interfaces at all points. This is a solid general pattern and will
help identity designers anyway.

**Comment by lahollen** [comment]
OK I'll propose that - but can I still get a sense of what would be needed? I'm guessing colors, fonts, SPL logo. SPL's website developer has asked.

**Comment by mbrakken** [comment]
@prestonaustin sounds right to me.

@lahollen Logo is the main thing. If they're strongly opinionated on colors and fonts I'll listen. RE: fonts, I'm not in favor of setting up integrations with common font services. If they want something that's not a standard webfont (my preference), I'll want to be able to deliver a set directly from our server.

**Comment by lahollen** [comment]
@mbrakken Here are links to the Playback logos in the shared Google Drive folder. Let me know if there's anything else you need.

https://drive.google.com/open?id=0B2JtTtreF1Szay1KYjhEX0pESlZ0TWU3TjhBZ1NVNWdnWnZZ

https://drive.google.com/open?id=0B2JtTtreF1SzSDJ2UlpHdEVIcHlsR1FvMGVGR0JDaGNud1lv

**Comment by lahollen** [comment]
@mbrakken And here are the links to different sizes/versions of the Seattle PL logos for the footer:

https://drive.google.com/open?id=0B2JtTtreF1SzRnpRck5QZ0VpTWVDMkgzbTljb2ZIenp1WHZz

https://drive.google.com/open?id=0B2JtTtreF1SzaUtQTTkySzdNSzNocExiY0hEVGxQOS1tVVZz

https://drive.google.com/open?id=0B2JtTtreF1SzTWQyVDhZa2E1cEVZZjZEMkU5bzVlR284eUVr
