### ISSUE TITLE
Date/time of submission not showing up in jurying

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#60]
Some of the submissions in the admin/jury interface read "Submitted no date" rather than with date/time of submission. Observed on the albums THE HOODED PINK FALCON,  BELIEVE, and A LITTLE ILLUSION.

Mac OS, Firefox 46.0.1, 5/11 11:45am CT. I'm signed in as admin user Valerie Wonder.

**Comment by prestonaustin** [comment]
I think we are trusting client dates for when they started the submission
as we try to have client context drive things and do the work to get that
right, but I'm thinking about switching to server-determined dates cuz the
client dates have been, to use the technical term, totes whack. Fixing that
is a rabbit hole I don't want to climb down just now, so I'll do the easier
thing.
