### ISSUE TITLE
Artist-provided text not always showing up complete in jurying

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#64]
For artists who provided a LOT of text in the 2 descriptive fields on the submission form, it appears that the jury interface may not be displaying all the text provided, arbitrarily cutting off the text provided for the playing-out field. I noticed it for PIANO CONCERTO--HOUSTON by BYRON AL YOUNG, and possibly THE WATER'S EDGE by MARCH TO MAY.

Mac OS, Firefox, 4/18, 11:11 CT. Signed in as admin user Valerie Wonder.

**Comment by lahollen** [comment]
For the record, I'm not totally clear that this is a system and not artist error but recording it here in case. For a counter-example, see PRESENT DAY by NORMAN BAKER & THE BACKROADS, which has a lot of text that shows up completely in jurying.

**Comment by prestonaustin** [comment]
I'll look at this and make sure there isn't an obvious display error, but I
suspect it is a data entry problem not a data lost or hiding issue. I may
need a smoking gun "I pasted this in and we got that instead" example.

**Comment by lahollen** [comment]
I've gone through almost the entire list (to help prepare SPL for jurying) and this doesn't seem like an issue anywhere but in the 2 albums I listed in my first comment. I'm going to assume this is a data entry problem and close. Let's re-open if it surfaces as a clear lost data issue.
