### ISSUE TITLE
Close submissions morning of Tues 5/24

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#67]
Public-facing sites list closing date for submissions as Mon. 5/23, but we will technically close on the morning of Tues. 5/24. I will update here with SPL-approved copy for homepage and any other necessary copy edits by Monday.

**Comment by lahollen** [comment]
Here is the link to a Google Doc with copy edits for the post-submissions site, including new text for homepage, /submit, and a few edits to /about and /faq:

https://docs.google.com/document/d/1c5RoKUG14BCNaWCndm5cnUHMwufjeRVmDLeCu7r9riU/edit#heading=h.1rwy45l9rq2j

I tried to make changes as clear as possible. Let me know if there are any questions.

**Comment by lahollen** [comment]
@whblondeau SPL made a few additional tiny edits to the post-submissions homepage copy since I posted that link above. I updated the GDoc around 1:15pm CT. Shouldn't impact your work unless you've already inputted that copy. I can itemize the edits if needed.

**Comment by whblondeau** [comment]
No problem, Lisa -- I had to scoot across town (remembered I needed to pick
up a prescription) and am just *finally* settling in.

Thanks,
Bill
