### ISSUE TITLE
Remove/change last remnants of CCR skin in admin

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#68]
In invite stage, the button to invite artist still reads "Invite to CCR." Change to "Invite to PlayBack" or simply "Invite."

In "Review & Publish" there's a poster sorting button that can be removed.

**Comment by prestonaustin** [comment]
Fixed.
Poster control display in Review & Publish is now conditional on {{#if postersEnabled}}
Invite to CCR changed to "Invite Artist"
