### ISSUE TITLE
Replace email copy for invites, deferrals, reminders, & final submission confirmation

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#69]
SPL is currently reviewing copy for emails that go out to artists in the invitation phase. I'll post links to the content in Google Drive here when it has been approved.

**Comment by lahollen** [comment]
@whblondeau Here are the links to the approved copy for the 4 emails I'm aware of:

Acceptance/invitation letter: https://docs.google.com/document/d/1xfxxmvUHvzhrx8vjL-luMYApiqOUeoKX4QdZ7opuXPs/edit#heading=h.czx0b0b1570f

Rejection/deferral letter: https://docs.google.com/document/d/1UmZzTIN6swCZ2eWsH_ZTHr6BXqkGWXdWeVTnvtFna8g/edit#

Reminder email for accepted artists: https://docs.google.com/document/d/1Lz9tDqVefIh8KjR2XfTuU70mxwPZ6HshiFToRUVaTTA/edit

Submission confirmation: https://docs.google.com/document/d/1u7AF9GibscZro_CRKg5H7sElpSeqyraSiq8Bttb5Uxw/edit#

**Comment by whblondeau** [comment]
I just issued a Pull Request for the content in /contents/emails only. If I need to add the corresponding changes to /public/templates/emails I will.

Changes [can be previewed at the task branch](https://github.com/whblondeau/seattle-public-library-client/tree/invitations_content/content/emails) on my fork.
