### ISSUE TITLE
Get domain name

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#7]
Decide on domain name and how SPL wants to host the site in conversation with our contact there.

**Comment by lahollen** [comment]
@prestonaustin and @mbrakken - we now have a DNS contact at SPL. Would one of you be willing to get in touch with her to work out how the site will be hosted? Contact info is in shared Drive folder for Seattle PL>General Resources and Templates or I can email to you.

**Comment by prestonaustin** [comment]
We'll commence setup for this Monday. What name will be used?

**Comment by andrewharbison** [comment]
Preston - we should have a name this week.

**Comment by andrewharbison** [comment]
We have a name. The project will be called Sound Waves.

**Comment by lahollen** [comment]
@andrewharbison are you still planning to make this site a subdomain of spl.org? How about: soundwaves.spl.org?

**Comment by andrewharbison** [comment]
This is the plan - we'll have our site developer on the call today to discuss.

**Comment by lahollen** [comment]
@andrewharbison  - I'm not in office this morning and can't offer much development insight on my own. @prestonaustin is conferring with our development team to clarify what exactly is needed, and should be able to contact your developer today. Does that work?

**Comment by lahollen** [comment]
We can also re-schedule our meeting to include a Rabble developer if that makes more sense

**Comment by andrewharbison** [comment]
If we can have a call today to just go over some basics that would be good - really just focusing on the essential components of squarespace site for now to move ahead towards submission. Call still ok ofr 9:30?

**Comment by lahollen** [comment]
Yes sounds good - and let's plan a meeting with Rabble devs for next week.

**Comment by andrewharbison** [comment]
ok - great.

**Comment by lahollen** [comment]
@prestonaustin - @lisazicherman is awaiting for details on DNS from you to get this set up. She will be out of office Tuesday and Wednesday of this week I believe. Can you update here? Thanks
