### ISSUE TITLE
Copy/modifications to complete submission form

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#70]
The "complete submission" form for invited artists needs to be updated for PlayBack. I will update here and reassign when I have edits approved by SPL.

**Comment by lahollen** [comment]
Here are the approved copy-edits from SPL for the complete-submission form:
https://docs.google.com/document/d/10uUWjUuzvIHAMGC13-g5FXoploLapdEXs5vnwoe4qgY/edit#

I haven't yet tried to master markdown, but I tried to make all changes clear. If there's any confusion, it may help to look at the doc I gave SPL with the full text: https://docs.google.com/document/d/1wNP4VQx1dpIkm-EM3Xx_LIZlI_XC8YUk19SjyqLqGVM/edit#heading=h.hqc77ckkp23

**Comment by prestonaustin** [comment]
- [ ] REPLACE “We’ll use this information to create an artist profile and promote you through .” WITH “We’ll use this information to create an artist profile and promote you through PlayBack.”

 - [ ] REPLACE “Artist name” WITH “Artist or ensemble name”

**Comment by whblondeau** [comment]
Checklist:
Artist information
 - [] REPLACE “We’ll use this information to create an artist profile and promote you through .” WITH “We’ll use this information to create an artist profile and promote you through PlayBack.”

 - [] REPLACE “Artist name” WITH “Artist or ensemble name”

 - [] REPLACE “Family-friendly EPL events” WITH “Family-friendly events at The Seattle Public Library”

 - [] REPLACE “EPL events with adult audiences” WITH “Library events with adult audiences”

 - [] REPLACE “strives to represent the diversity of Edmonton’s music scene” WITH “PlayBack strives to represent the diversity of Seattle’s music scene.”

 - [] REPLACE “All information submitted to this form is subject to Edmonton Public Library’s Confidentiality Statement.” WITH “All information submitted to this form is subject to [The Seattle Public Library's Confidentiality of Patron Information] <http://www.spl.org/about-the-library/library-use-policies/confidentiality-of-patron-information>.”
Your License (unfinished form)
 - [] REPLACE ALL TEXT ON THIS FORM WITH 
Please complete your album and artist data and upload your tracks before agreeing to a license. You will be able to choose between two licensing term options: [five-year] <https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit?usp=sharing> and [perpetual] <https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit?usp=sharing>. You will also receive a $200 honorarium for sharing your music through PlayBack.

If the license is not appearing and your album and artist information is complete, please try refreshing the page.
Your License (ready to sign)
 - [] REPLACE “Please complete the following details and review the license below. We will send your payment to the address you provide. By clicking "Sign and Submit License" at the bottom of the page, you acknowledge that you have read, understand and agree with the terms stipulated below.” WITH “Please complete the following details and review the license. We will send your payment to the address you provide. By clicking "Sign and Submit License," you acknowledge that you have read, understand, and agree with the terms stipulated.”

 - [] REPLACE “Province” WITH “State”

 - [] REPLACE “Postal code” WITH “Zip code”

 - [] REPLACE ALL THIS “PLAIN LANGUAGE” TEXT: 
“This license summary is non-binding, we encourage you to read the full license below.

EPL can:
make your content available for permanent download and streaming to site users.
promote your content as a part of the site.
integrate your content into new parts of the site as they are developed.
You:
confirm that you have the right to license all the content you are sharing, including cover songs and album art.
continue to own all the rights to the content. The agreement is non-exclusive so you can share or sell your content anywhere else you want.
can ask us to take your content off the site after two years. Just email localmusic@epl.ca and EPL will take it down.
will be given a one-time payment for your contribution. Your honorarium amount is listed in the Schedule of Royalties.”
WITH
“This license summary is non-binding, we encourage you to read the full license. There are two licensing term options to choose from: five year and perpetual – both will allow Library cardholders to stream music and download; those who download your music can enjoy it as long as they want for their personal use.

The Seattle Public Library’s PlayBack:
Makes your content available for permanent download and streaming to site users.
Promotes your content as a part of the site.

You:
Confirm that you have the right to license all the content you are sharing, including cover songs and album art.
Continue to own all the rights to the content. The agreement is non-exclusive so you can share or sell your content anywhere else you want.
Choose to license your music for a perpetual or five year term. If you choose a five year term, you can ask us to take your content off the site after five years. Just email playback@spl.org and we will take it down.
Will be given a one-time payment of $200 for your contribution, if accepted.”
ADD NEW SUB-SECTION WITH CAPABILITY FOR ARTISTS TO CHOOSE BETWEEN THE 2 LICENSES. SUGGESTED COPY AND FORMATTING:
Select Your License
--------------------------
Choose one of the following licensing agreements, and review closely the license that is created for you.
[Five-year term license] <https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit?usp=sharing> 
[Perpetual term license] <https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit?usp=sharing>

Optional [Creative Commons Attribution 4.0 International Public License] <https://creativecommons.org/licenses/by/4.0/>
Include Creative Commons Attribution 4.0 International Public License

[SELECTED AND COMPLETED LICENSE]

**Comment by prestonaustin** [comment]
@whblondeau Please confirm this is done only after you finish license selection, then close it.
