### ISSUE TITLE
Add "spoken languages" field to complete submission form

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#74]
Add a field for spoken languages to the /complete-submission Album information form. Comma separated, include English.

**Comment by prestonaustin** [comment]
ADDRESS THIS ISSUE ONLY AFTER LICENSE SELECTION (ISSUE 20) IS COMPLETE, TESTED, AND ON A PR

**Comment by whblondeau** [comment]
Closed by PR#92. Working data save/retrieve, although not enforcing proper comma-delimited form.
