### ISSUE TITLE
Banner carousel for playback.spl.org

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#78]
I've requested images and text from SPL for a 3-banner rotation on the PlayBack homepage. @kellyhiser or I will update here with files when received.

**Comment by kellyhiser** [comment]
- [ ] change the color of the text boxes to the yellow demonstrated in this PDF (if color details will make this easier, lmk and I can get that from SPL's graphic designer):
[playback rabble banners comp with text boxes.pdf](https://github.com/therabble/seattle-public-library-client/files/363656/playback.rabble.banners.comp.with.text.boxes.pdf)

- [ ] change the text color to black 

- [ ] update banner content as detailed below (or provide SPL with banner CMS and I'll walk them through the process)


**Banner 1**

Text:
Local Music
Stream and download tracks selected by local jurors
Listen [links to album page]

Image:
![spl playback rabble banner 1](https://cloud.githubusercontent.com/assets/8515447/16839003/8f18da8e-499a-11e6-833d-98febc649b99.jpg)

**Banner 2**
Text:
Seattle Artists
Discover the local musicians in our collection
Explore [links to artist page]
 
Image:
![spl playback rabble banner 2](https://cloud.githubusercontent.com/assets/8515447/16839033/bca9ef1a-499a-11e6-8f50-43e088c52c9e.jpg)

**Banner 3**

Text:
About PlayBack
Learn about the Library’s online local music collection
Read [links to "about"]

Image:
![spl playback rabble banner 3](https://cloud.githubusercontent.com/assets/8515447/16839044/cf46e3ee-499a-11e6-8710-2fd0c03af321.jpg)
