### ISSUE TITLE
Set up pre-launch placeholder site

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#8]
Set up a public-facing placeholder site (possibly thru Squarespace) announcing the project and with basic information and contacts for musicians, librarians, and the public.

**Comment by lahollen** [comment]
Depends on #3, #12

**Comment by lahollen** [comment]
@andrewharbison I put together a working draft of some copy we could use for the pre-launch site, based on Edmonton's site at https://capitalcityrecords.squarespace.com/

Here is the link to the Google Doc (also in our shared Drive folder):
https://docs.google.com/document/d/13MIbbBaSDXHx0L4vhQ9EaeJKxXn5svp1AL3FSVqnt8U/edit?usp=sharing

Unknowns are in brackets, and everything is fully modifiable to reflect however SPL wants to describe and frame the project. My aim is just to help expedite the process if possible. Dependencies listed above are still in effect.

**Comment by andrewharbison** [comment]
This is a great start. I will add some language I have and run it by our Communications office for approval today.

**Comment by lahollen** [comment]
Site in progress here: http://splsoundwaves.squarespace.com/
Password: splsoundwaves

**Comment by andrewharbison** [comment]
Great start!

**Comment by lahollen** [comment]
Update: I've added Lisa Z. and @andrewharbison as admin contributors to this site. Lisa Z. will do design work and Andrew will provide and edit needed content (can put up directly or send to me to put up). DNS setup needed to direct soundwaves.spl.org to this site.

**Comment by lahollen** [comment]
Update: SPL will host this on their own site. Content currently in progress.

**Comment by lahollen** [comment]
Update: SPL will launch with start of promotion for submissions. Date still TBD.

**Comment by lahollen** [comment]
Now live: www.spl.org/playback --> http://www.spl.org/library-collection/books-movies-and-music/playback
