### ISSUE TITLE
edits needed for invite go-live

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#83]
as of my first round of testing c. 8:30 ET Monday June 27:
- [ ] invite email sez due date for completing submissions is July 1, should be July 11, see #82 
- [ ] invite email signature shows the break command after "Kreg Hasegawa | Emerging Technologies Lead", "Virtual & Instruction Services", and "The Seattle Public Library"  I can't figure out how to get break to show up here without it just making a break, but you know: < br / >
- [ ] on the confirmation page after signing a license the contact email is still EPL's, change to playback@spl.org

otherwise, everything went very smoothly.

**Comment by lahollen** [comment]
@kellyhiser SPL's license doesn't specify if tracks must be listed ("Album or Track Title(s)") but I have assumed it would list tracks a la CCR, unless MPL lists album title only on their licenses (SPL's license is meant to closely model the latter).

**Comment by kellyhiser** [comment]
YML's license doesn't list tracks. removing that item from the list.

**Comment by kellyhiser** [comment]
closing and moving these items to #84 and #86 to make this easier to see for dev, i hope.
