### ISSUE TITLE
Artist banner image failed to display and upload

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#85]
Testing on wax. 6/27 circa 9:40PM CT. Mac OS Firefox.

I successfully uploaded an artist banner image file to the complete submission form and selected a thumbnail. All displayed well. But when I returned later to the form after signing and submitting the license, the banner image did not display, and displayed a broken image icon instead. I attempted to update the image but the second upload of the same file never completed, and the uploading bar remained stagnant on the screen.

![screen shot 2016-06-27 at 9 49 00 pm](https://cloud.githubusercontent.com/assets/13225403/16402296/00567022-3cb1-11e6-817e-e258f4b2e67b.png)

**Comment by lahollen** [comment]
I accessed the account from Safari 9.1.1 and banner image does not display:

![screen shot 2016-06-27 at 9 53 19 pm](https://cloud.githubusercontent.com/assets/13225403/16402368/aa01e16a-3cb1-11e6-8314-104635c6ae35.png)

Also this is the file I've attempted to upload:

![img_0022](https://cloud.githubusercontent.com/assets/13225403/16402387/ce391bc0-3cb1-11e6-9479-085105bc6c14.jpg)

**Comment by lahollen** [comment]
I also noticed that the email confirmation I received after signing my license listed this under "Banner image"--rather than the .jpg file name I expected to see--in list of "Artist Information Received":

Banner image: {"url":"/org.spl.playback-jsfs/complete-submission/lisa-hollenbach-test-for-email/notley-alice_05_i-the-people_upenn_11-6-06--1467080047000.mp3","created":1467080047578,"version":0,"private":false,"encrypted":false,"fingerprint":"eaaa1cbabd0c8e7fba2beff7bcab8696f06d2f03","access_key":"eaaa1cbabd0c8e7fba2beff7bcab8696f06d2f03","content_type":"application/octet-stream","file_size":0,"block_size":1048576,"blocks_replicated":0,"inode_replicated":0,"blocks":[]}

I'm not sure if this is related or a separate issue but recording here for now.

**Comment by kellyhiser** [comment]
i haven't been able to duplicate this behavior. ran through several quick uploads and everything worked. this should be last priority and not delay invite go live.

**Comment by kellyhiser** [comment]
guessing this was a file size or network issue. closing.
