### ISSUE TITLE
License form displays even when other req. data not complete

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#90]
In the complete submission forms, the "Your License" section fully displays and can be completed even if the other 3 sections are incomplete. In CCR, this section would only fully display if all other required information was filled out. I assume we want the same for SPB but @prestonaustin or @kellyhiser can you confirm? Rationale here being that we don't want artists signing a license before they've uploaded tracks or images.

This would be the full copy for what would display under "Your License" when other forms are incomplete: 

Please complete your album and artist data and upload your tracks before agreeing to a license. You will be able to choose between two licensing term options: [five-year] <https://drive.google.com/file/d/0B2JtTtreF1SzOWsxeHM4aG15YjA/view> and [perpetual] <https://drive.google.com/file/d/0B2JtTtreF1SzVW5HRTRjZTBvWXc/view>. You will also receive a $200 honorarium for sharing your music through PlayBack.

If the license options are not appearing and your album and artist information is complete, please try refreshing the page.

**Comment by whblondeau** [comment]
Yikes! I thought it was supposed to.

I can suppress that, if that's what we want. I just need to know exactly
what I'm supposed to do: under what logical conditions to we want the
license to be displayed, and under what conditions do we want it not
displayed?

**Comment by kellyhiser** [comment]
actually, I'm seeing that the license does NOT display if the other sections are incomplete. there's no copy under license in these cases, just a blank page. 

Bill, we want the license to be displayed when the required fields (marked with *) in Artist, Album and Tracks are completed (for Tracks that just means that a track is uploaded). Again, I *do* think it is working this way, and that the page is just missing copy.

**Comment by lahollen** [comment]
Weird. I definitely saw the displayed license but now when I look back I see old CCR copy (not a blank page): 

Please complete your album and artist data and upload your tracks before agreeing to the license.
License Agreement
Schedule of Royalties (Honorarium Amounts)

If the license is not appearing and your album and artist information is complete, please try refreshing the page.

**Comment by whblondeau** [comment]
So, Lisa: this was the license page for someone who had failed to fill out
the required artist and album data?

I think there's a logic problem I need to fix. I have this being displayed
when the license is "not ready for review":

Please complete your album and artist data and upload your tracks before
agreeing to a license. You will be able to choose between two licensing
term options: five-year
<https://docs.google.com/document/d/11WCcyKLsyCJKWgdskTHOOFM1b7lIWJ9SMKeZdlLbpyY/edit>
and perpetual
<https://docs.google.com/document/d/1g8mwHMBbHb4RzahsQWmrY64FH7f2yINAuzZ2nf8Etck/edit>.
You will also receive a $200 honorarium for sharing your music through
PlayBack.

If the license is not appearing and your album and artist information is
complete, please try refreshing the page.

(EXCEPT that I spotted and fixed a bug that would have messed up the
"perpetual" link, but that would not have affected the display logic.)

I will try to find the source of the CCR language and fix that.

-Bill
